baseURL: https://seb73701.github.io/mydevops-wik/
languageCode: fr-fr
title: 'MyDevops-Wik'

#---- THEMES
theme: 'mydevops-wik'
#theme: 'blowfish'

#---- CACHES
caches:
  images:
    dir: :cacheDir/images
